import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import Header from '../components/Header'
import useSearch from '../hooks/useSearch';
import styles from '../styles/Home.module.css'
import { parseProperties } from '../utils/parse-properties';
import stringSearch from '../utils/stringSearch';
import { getCompanies } from './api/getCompanies';

export async function getStaticProps() {
  const database = await getCompanies();
  console.log('database')
  const posts = parseProperties(database);

  return {
    props: {
      posts,
    },
  };
}

export default function Home({posts}: {posts: {id: string, name: string, slug: string, logo:string}[]}) {
  console.log('posts', posts)
  const {textSearch} = useSearch();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Header/>
      <main className={styles.main}>
        <div className={styles.grid}>
        {
        posts.filter(({name}) => stringSearch(name, textSearch)).map(({id, name, slug, logo}) => (
          <Link href={`company/${slug}`} className={styles.card} key={id}>
            <Image src={logo ?? ''} width="70" height="70"alt={`${name} logo`}/>
            <h2>{name} &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </Link>
        ))
      }
    
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}


