import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import Header from '../components/Header'
import useFavorites from '../hooks/useFavorites';
import useSearch from '../hooks/useSearch';
import styles from '../styles/Home.module.css'
import { parsePlaces } from '../utils/parsePlaces';
import stringSearch from '../utils/stringSearch';
import { getCompanies } from './api/getCompanies';
import Place from '../components/Place';
import { getCategories } from './api/getCategories';
import { parseCategories } from '../utils/parseCategories';
import PlaceFull from '../components/PlaceFull';
import { FC } from 'react';
import { Place as TypePlace } from '../types/Place';
import { Category as TypeCategory } from '../types/Category';

export async function getStaticProps() {
  const companiesDatabase = await getCompanies();
  const categoriesDatabase = await getCategories();
  // console.log('database')
  const companies = parsePlaces(companiesDatabase);
  const categories = parseCategories(categoriesDatabase);

  return {
    props: {
      companies,
      categories
    },
  };
}

type Props = {
  companies: TypePlace[];
  categories: TypeCategory[]
};

const Home:FC<Props> = ({companies, categories}) => {
  // console.log('posts', posts)
  const {textSearch} = useSearch();
  const { favorites } = useFavorites();
  return (
    <div className={styles.container}>
      <Head>
        <title>Ondié</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Header/>
      <main className={styles.main}>
      
      <div className={styles.gridWrapper}  style={{maxWidth: '100vw'}}>
        <div className={styles.grid}>
          {
            categories.map(({id, name, slug, image}) => (
              <Link href={`categories/${slug}`} key={id} className={styles.categoryItem}>
                <Image className={styles.categoryImage} src={image ?? ''} width={80} height={80} alt={`${name} logo`}/>
                <p className={styles.categoryName}>{name}</p>
              </Link>
            ))
          }
        </div>
          </div>
          {
            favorites.length > 0 && (
              <>
              
<h2 className={styles.placeTitle}>Seus favoritos</h2>
<div className={styles.gridWrapper}>
        <div className={styles.grid}>
          <div className={styles.favorites}>
          {
        favorites.slice(0,4).map((item) => (
          <PlaceFull item={item} key={item.id}/>
        ))
      }
</div>
</div>
          </div>
          </>
            )
          }
          
      <h2 className={styles.placeTitle}>Lojas</h2>
        <div className={styles.gridWrapper}>
        <div className={styles.grid}>
        {
        companies.filter(({category}) => category === 'shopping').filter(({name}) => stringSearch(name, textSearch)).map((item) => (
          <Place item={item} key={item.id}/>
        ))
      }
    
        </div>
        </div>
        <h2 className={styles.placeTitle}>Restaurantes</h2>
        <div className={styles.gridWrapper}>
        <div className={styles.grid}>
        {
        companies.filter(({category}) => category === 'food').filter(({name}) => stringSearch(name, textSearch)).map((item) => (
          <Place item={item} key={item.id}/>
        ))
      }
    
        </div>
        </div>
        <h2 className={styles.placeTitle}>Museu</h2>
        <div className={styles.gridWrapper}>
        <div className={styles.grid}>
        {
        companies.filter(({category}) => category === 'museum').filter(({name}) => stringSearch(name, textSearch)).map((item) => (
          <Place item={item} key={item.id}/>
        ))
      }
    
        </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home;

